### ISSUE TITLE
Недочеты

### ISSUE THREAD

**Issue by LidiaIvanova** [kralonur/Kotlin-Calculator#1]
Эти поля тоже должны быть приватными.
https://github.com/kralonur/Kotlin-Calculator/blob/f1c9746e26985983c3cac24bde7785c99d7b2ebb/app/src/main/java/com/example/kotlincalculator/MainActivity.kt#L11
https://github.com/kralonur/Kotlin-Calculator/blob/f1c9746e26985983c3cac24bde7785c99d7b2ebb/app/src/main/java/com/example/kotlincalculator/MainActivity.kt#L12

Тип переменной везде явно указывать необязательно.
https://github.com/kralonur/Kotlin-Calculator/blob/f1c9746e26985983c3cac24bde7785c99d7b2ebb/app/src/main/java/com/example/kotlincalculator/MainActivity.kt#L21

Для проверки непустоты строки есть специальный метод isNotEmpty(), причем Android Studio на это указала
https://github.com/kralonur/Kotlin-Calculator/blob/f1c9746e26985983c3cac24bde7785c99d7b2ebb/app/src/main/java/com/example/kotlincalculator/MainActivity.kt#L35

Отлично, что сделал обработку сохранения состояния при перевороте экрана и отдельный layout.

Нужно следить за warnings от Android Studio. Она часто советует правильные вещи.

Называй переменные правильно. d - плохое название для переменной.

**Comment by kralonur** [comment]
Issue solved
